apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: mybackend:1.0
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: MONGODB_URI
          value: "mongodb+srv://322103310091_db_user:VPHXUluz1SAOZjf0@cluster.8nyzn7c.mongodb.net/?retryWrites=true&w=majority&appName=cluster"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
