version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "8000:8000"          # backend accessible on host port 8000
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb+srv://322103310091_db_user:VPHXUluz1SAOZjf0@cluster.8nyzn7c.mongodb.net/?retryWrites=true&w=majority&appName=cluster
    volumes:
      - ./server:/app        # live reload

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"          # Vite dev server
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app       # live reload
